### ISSUE TITLE
Maximum recursion depth exceeded error

### ISSUE THREAD

**Issue by eldudemeister** [aegjoyce/custom-ambilight#1]
Hi, loving this, managed to install this but I'm getting the below error...my TV is a Philips OLED 48/808....any help gratefully received...
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:43:14 (5 occurrences)
Last logged: 20:46:22

[140220322288576] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 627, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/custom_ambilight/light.py", line 81, in async_turn_on
    await self.api.turn_on(**kwargs)
  File "/config/custom_components/custom_ambilight/api.py", line 253, in turn_on
    await self.turn_on(**self.previous_state)
  File "/config/custom_components/custom_ambilight/api.py", line 253, in turn_on
    await self.turn_on(**self.previous_state)
  File "/config/custom_components/custom_ambilight/api.py", line 253, in turn_on
    await self.turn_on(**self.previous_state)
  [Previous line repeated 985 more times]
  File "/config/custom_components/custom_ambilight/api.py", line 186, in turn_on
    current_brightness = self.get_brightness()
                         ^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```

**Comment by aegjoyce** [comment]
I think your TV is too new if it’s an OLED808, they stopped including the jointspace API a couple of years ago. 

You can test by going to http://your-tv-ip-address:1925/ambilight/currentconfiguration

If it returns some JSON then you have jointspace, if not I’m afraid you’re out of luck

**Comment by eldudemeister** [comment]
Ah that's a shame, tried that link and I don't get any JSON...thanks for the quick reply though...

**Comment by bjornorri** [comment]
I have a Philips `65OLED808/12` and it has the API. I'm getting the same error when invoking the `light.turn_on` action without any parameters:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 626, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/custom_ambilight/light.py", line 81, in async_turn_on
    await self.api.turn_on(**kwargs)
  File "/config/custom_components/custom_ambilight/api.py", line 253, in turn_on
    await self.turn_on(**self.previous_state)
  File "/config/custom_components/custom_ambilight/api.py", line 253, in turn_on
    await self.turn_on(**self.previous_state)
  File "/config/custom_components/custom_ambilight/api.py", line 253, in turn_on
    await self.turn_on(**self.previous_state)
  [Previous line repeated 985 more times]
  File "/config/custom_components/custom_ambilight/api.py", line 186, in turn_on
    current_brightness = self.get_brightness()
                         ^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```
